name: Latest blog post workflow
on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual trigger

jobs:
  update-readme-with-blog:
    name: Update README with Hashnode Posts
    runs-on: ubuntu-latest
    permissions:
      contents: write # Crucial: Allows the bot to edit your README
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          # Standard Hashnode RSS format
          feed_list: "https://tiffexplores.hashnode.dev/rss.xml"
